name: '🚔'

on: [ push, pull_request ]

jobs:

  job:
    name: verify ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11, 17 ]
      fail-fast: true

    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Drop JVM config
        if: matrix.java == '8'
        run: rm -f .mvn/jvm.config

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'

      - name: Maven verify
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
