name: '🚓'

on: push

jobs:

  job:
    name: ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
      fail-fast: true

    steps:

      - name: Git
        uses: actions/checkout@v2

      - name: Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
          distribution: 'adopt'
          check-latest: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: Test
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
